version: "3.9"

services:
  redis:
    image: redis:alpine

  celery:
    build: .
    command: celery -A bhavcopy worker -l info
    volumes:
      # - ./bhavcopy/:/usr/src/app/web/
      - ./bhavcopy/:/home/app/web/
    env_file:
      - ./.env.dev
    depends_on:
      - redis
      - web

  celery-beat:
    build: .
    command: celery -A bhavcopy beat -l info
    volumes:
      # - ./bhavcopy/:/usr/src/app/web/
      - ./bhavcopy/:/home/app/web/
    env_file:
      - ./.env.dev
    depends_on:
      - redis
      - web

  web:
    build: .
    command: gunicorn bhavcopy.wsgi:application --bind 0.0.0.0:8000
    volumes:
      # - ./bhavcopy/:/usr/src/app/web/
      - ./bhavcopy/:/home/app/web/
      - media_volume:/home/app/web/media
      - static_volume:/home/app/web/static
    env_file:
      - ./.env.dev
    expose:
      - "8000"
    # ports:
    #   - "8000:8000"
    depends_on:
      - redis

  nginx:
    build: ./nginx
    volumes:
      - media_volume:/home/app/web/media
      - static_volume:/home/app/web/static
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  redisdata:
  media_volume:
  static_volume:
